### ISSUE TITLE
"Use strict" would allow usage in VSTS build tasks

### ISSUE THREAD

**Issue by jessehouwing** [download13/uuidv5#1]
I'm trying to use your module as part of a VSTS build task, but run into the following error when doing so:
```
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

Adding:

```
"use strict";

const crypto = require('crypto');
```

solves my issue, would it be possible to make this part of the module?

**Comment by download13** [comment]
Can doodly. https://github.com/download13/uuidv5/commit/a19961290aa5749b5a1e918aaa63ee2463682388 closes this.

**Comment by jessehouwing** [comment]
Thanks!
